GeoUsage updates from ES parsing
geopython/GeoUsage pull request #9
Opened 2019-08-08 19:10 UTC by kngai

- Parsing fix for kvp
- Fix to error checks and handling
- Improved logger messages
- Parse the full user_agent details as the 12th token to end of log line
- Added IP number (derived from IP address) as part of OWSLogRecord class
- Added `crs`, `format`, `ows_resource` and `styles` as part of OWSLogRecord class
- `ows_resource` parsing compiled as one for the keys: `layer`, `layers`, `typename` and `coverageid`
- `crs` parsing compiled as one of the keys: `crs` and `subsettingcrs`
- `format` parsing compiled as one of the keys: `format` and `outputformat`
- Analyzer class fix for using non-WMSLogRecord or WMSLogRecord class type
- Added top user agents to GeoUsage log analyze command
- run_tests.py to elapsed times for slow unit tests after a set SLOW_TEST_THRESHOLD
- run_tests.py fix to open/read access_log and correct unit test cases

2019-09-04 17:33 UTC, tomkralidis requested changes

2019-09-04 17:33 UTC, tomkralidis commented on GeoUsage/log.py
> +def dot2LongIP(ip):
keep function names lowercase? `def dot2longip(ip):`

2019-09-04 17:33 UTC, tomkralidis commented on GeoUsage/tests/run_tests.py
> +    def startTest(self, test):
`def start_test(self, test):`

2019-09-04 17:33 UTC, tomkralidis commented on GeoUsage/tests/run_tests.py
> +    def addSuccess(self, test):
`def add_success(self, test):`

2019-09-04 17:33 UTC, tomkralidis commented on GeoUsage/tests/run_tests.py
> +    def startTest(self, test):
or do `startTest` and `addSuccess` override specific methods in `TextTestResult` ?

2019-09-09 14:44 UTC, kngai commented
Changes requested have been pushed out (forced)

2019-09-09 15:13 UTC, merged